version: '3.5'

services:
    mongo:
        container_name: thx_mongo
        image: mongo
        ports:
            - 27017:27017
        environment:
            MONGO_INITDB_ROOT_USERNAME: root
            MONGO_INITDB_ROOT_PASSWORD: root
            MONGO_INITDB_DATABASE: api

    mongo-express:
        container_name: thx_mongo_express
        image: mongo-express
        logging:
            driver: none
        ports:
            - 8081:8081
        environment:
            ME_CONFIG_MONGODB_ADMINUSERNAME: root
            ME_CONFIG_MONGODB_ADMINPASSWORD: root

    node:
        container_name: thx_node
        image: node:12
        volumes:
            - ./:/usr/src/service
        working_dir: /usr/src/service
        command: bash -c "npm install && npm run watch:debug"
        depends_on:
            - ganache
            - mongo
        links:
            - mongo
            - ganache
        ports:
            - 3000:3000

    ganache:
        container_name: thx_ganache
        image: trufflesuite/ganache-cli:latest
        ports:
            - '8546:8545'
        volumes:
            - ./:/ganache_data
        command:
            [
                'ganache-cli',
                "--account='0x873c254263b17925b686f971d7724267710895f1585bb0533db8e693a2af32ff,100000000000000000000'",
                "--account='0xe9793d9246355c0f9fd3b330c0ee0aebdb24c813d47a27c1df87d6656c691d37,100000000000000000000'",
                "--account='0x447b6475b1170c4edd9521ba4960bbcf4252cec02b14e0564c87ec00624033a8,100000000000000000000'",
                "--account='0x1b8242ac13eb24f83479b3d9d83eabf484844de02708758c27142d0ed98aec2c,100000000000000000000'",
            ]
    influxdb:
        container_name: thx_influxdb
        build:
            context: .
            dockerfile: ./docker/Dockerfile.influxdb
        logging:
            driver: none
        ports:
            - '8086:8086'
    grafana:
        container_name: thx_grafana
        build:
            context: .
            dockerfile: ./docker/Dockerfile.grafana
        logging:
            driver: none
        links:
            - influxdb
        environment:
            - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
            - GF_AUTH_ANONYMOUS_ENABLED=true
            - GF_AUTH_BASIC_ENABLED=false
        ports:
            - '8082:3000'
    k6:
        container_name: thx_k6
        build:
            context: .
            dockerfile: ./docker/Dockerfile.k6
        ports:
            - '6565:6565'
        volumes:
            - './test/load:/test/load'
        environment:
            - K6_OUT=influxdb=http://influxdb:8086/k6
        command: 'version'
