version: '3.5'

services:
    mongo:
        container_name: thx_mongo
        image: mongo
        ports:
            - 27017:27017
        environment:
            MONGO_INITDB_ROOT_USERNAME: root
            MONGO_INITDB_ROOT_PASSWORD: root
            MONGO_INITDB_DATABASE: api

    mongo-express:
        container_name: thx_mongo_express
        image: mongo-express
        ports:
            - 8081:8081
        environment:
            ME_CONFIG_MONGODB_ADMINUSERNAME: root
            ME_CONFIG_MONGODB_ADMINPASSWORD: root

    node:
        container_name: thx_node
        image: node:10
        volumes:
            - ./:/usr/src/service
        working_dir: /usr/src/service
        command: bash -c "npm install && npm run build && npm run serve"
        links:
            -   mongo
        ports:
            - 3000:3000

    ganache:
        container_name: thx_ganache
        image: trufflesuite/ganache-cli:latest
        ports:
            - "8545:8545"
        volumes:
            - ./:/ganache_data
