version: '3.5'

services:
    mongo:
        container_name: thx_mongo
        image: mongo
        ports:
            - 27017:27017
        environment:
            MONGO_INITDB_ROOT_USERNAME: root
            MONGO_INITDB_ROOT_PASSWORD: root
            MONGO_INITDB_DATABASE: api

    node:
        container_name: thx_node
        image: node:12
        volumes:
            - ./:/usr/src/service
        working_dir: /usr/src/service
        command: bash -c "npm run build; npm run deploy:factory; npm run watch:debug"
        depends_on:
            - mainnet
            - testnet
            - mongo
        links:
            - mongo
            - mainnet
            - testnet
        ports:
            - 3000:3000

    testnet:
        container_name: thx_testnet
        image: trufflesuite/ganache-cli:latest
        ports:
            - '8547:8545'
        volumes:
            - ./:/ganache_data
        command:
            [
                'ganache-cli',
                "--account='0x873c254263b17925b686f971d7724267710895f1585bb0533db8e693a2af32ff,100000000000000000000'",
            ]

    mainnet:
        container_name: thx_mainnet
        image: trufflesuite/ganache-cli:latest
        ports:
            - '8546:8545'
        volumes:
            - ./:/ganache_data
        command:
            [
                'ganache-cli',
                "--account='0x873c254263b17925b686f971d7724267710895f1585bb0533db8e693a2af32ff,100000000000000000000'",
            ]
