name: API CI

on: [push, pull_request]

jobs:
    build-node:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v1
            - name: Use Node.js 10.x
                uses: actions/setup-node@v1
                with:
                    node-version: 10.x
            - name: npm install, build-ts, and test
                run: |
                    npm install
                    npm run build-ts
                    npm test
                env:
                    CI: true    
