name: CI/CD

on:
    pull_request:
        branches:
            - develop

jobs:
    buildAndTest:
        name: CI Pipeline
        runs-on: ubuntu-latest
        strategy:
            matrix:
                node-version: ['10.x']

        steps:
            - uses: actions/checkout@v2

            # Initialize Node.js
            - name: Install Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v1
              with:
                  node-version: ${{ matrix.node-version }}

            # Install project dependencies, test and build
            - name: Install dependencies
              run: npm install
            - name: Run build
              run: npm run build
            - name: Run test
              run: npm run test
