name: CI

on: [push]

jobs:
    build-node:
        runs-on: ubuntu-latest

        steps:
            - uses: 'actions/checkout@v2'
            - name: Use Node.js 10.x
              uses: actions/setup-node@v1
              with:
                  node-version: 10.x
            - run: |
                  npm install
                  npm run build --if-present
                  npm run test
              env:
                  CI: true
