name: CI

on: [push, pull_request]

jobs:
    build-node:
        runs-on: ubuntu-latest

        steps:
            - uses: 'actions/checkout@v2'
            - name: Use Node.js 10.x
              uses: actions/setup-node@v1
              with:
                  node-version: 10.x
            - name: npm ci, build
              run: |
                  npm ci
                  npm run build --if-present
              env:
                  CI: true
